version: "3.7"

services:
    workspace:
        build:
            context: ./workspace
        volumes:
            - ${WORK_ROOT}:/var/www
        environment:
            - TZ=${TZ}
        tty: true

    # php56-fpm:
    #     build:
    #         context: ./php
    #         args:
    #             - PHP_VERSION_ARG=5.6
    #     volumes:
    #         - ${WORK_ROOT}:/var/www
    #     environment:
    #         - TZ=${TZ}
    # php72-fpm:
    #     build:
    #         context: ./php
    #         args:
    #             - PHP_VERSION_ARG=7.2
    #     volumes:
    #         - ${WORK_ROOT}:/var/www
    #     environment:
    #         - TZ=${TZ}
    # php73-fpm:
    #     build:
    #         context: ./php
    #         args:
    #             - PHP_VERSION_ARG=7.3
    #     volumes:
    #         - ${WORK_ROOT}:/var/www
    #     environment:
    #         - TZ=${TZ}
    php74-fpm:
        build:
            context: ./php
            args:
                - PHP_VERSION_ARG=7.4
        volumes:
            - ${WORK_ROOT}:/var/www
        environment:
            - TZ=${TZ}

    nginx:
        build:
            context: ./nginx
        volumes:
            - ${WORK_ROOT}:/var/www
            - ./log/nginx:/var/log/nginx
            - ./nginx/sites/:/etc/nginx/sites-available
        environment:
            - TZ=${TZ}
        ports:
            - "${NGINX_HTTP_PORT}:80"
            - "${NGINX_HTTPS_PORT}:443"
        depends_on:
            # - php56-fpm
            # - php72-fpm
            # - php73-fpm
            - php74-fpm

    postgres:
        build:
            context: ./postgres
            args:
                - POSTGRES_VERSION=${POSTGRES_VERSION}
        volumes:
            - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
        environment:
            - TZ=${TZ}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - ${POSTGRES_PORT}:5432

    # https://hub.docker.com/_/redis
    redis:
        image: redis:latest
        volumes:
            - ${DATA_ROOT}/redis:/data
        environment:
            - TZ=${TZ}
        ports:
            - "${REDIS_PORT}:6379"

    # https://hub.docker.com/r/minio/minio/
    # https://docs.min.io/docs/deploy-minio-on-docker-compose.html
    minio:
        image: minio/minio
        volumes:
            - ${DATA_ROOT}/minio/data:/data
        ports:
            - "${MINIO_PORT}:9000"
            - "${MINIO_CONSOLE_PORT}:9001"
        environment:
            - TZ=${TZ}
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
